//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentJournal
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int WaterId { get; set; }
        public int PayMethodId { get; set; }
        public int WaterCraftId { get; set; }
        public int InstructionTypeId { get; set; }
        public int InstructorId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Client Client { protected get; set; }
        public virtual Water Water { protected get; set; }
        public virtual PayMethod PayMethod { protected get; set; }
        public virtual WaterCraft WaterCraft { protected get; set; }
        public virtual InstructionType InstructionType { protected get; set; }
        public virtual Instructor Instructor { protected get; set; }
    }
}
