//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatercraftType
    {
        public WatercraftType()
        {
            this.WaterCraft = new HashSet<WaterCraft>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<WaterCraft> WaterCraft { protected get; set; }
    }
}
